package com.hand.hap.exception.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "act_exception")
public class Exception_dev extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_PROC_ID = "procId";
     public static final String FIELD_MESSAGE = "message";
     public static final String FIELD_DUEDATE = "duedate";


     @Id
     @GeneratedValue
     private Long id;

     @NotEmpty
     @Length(max = 225)
     private String procId; //流程id

     @Length(max = 2147483647)
     private String message; //异常信息

     private Date duedate;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setProcId(String procId){
         this.procId = procId;
     }

     public String getProcId(){
         return procId;
     }

     public void setMessage(String message){
         this.message = message;
     }

     public String getMessage(){
         return message;
     }

     public void setDuedate(Date duedate){
         this.duedate = duedate;
     }

     public Date getDuedate(){
         return duedate;
     }

     }
